# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         PDFLib-PPS
version:      0.04
version_from: lib/PDFLib/PPS.pm
installdirs:  site
requires:
    PDFLib:                        

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
